### ISSUE TITLE
A recent khard change breaks deoplete-khard

### ISSUE THREAD

**Issue by ghost** [nicoe/deoplete-khard#3]
A recent khard release removes `get_email_addresses()`, which breaks deoplete-khard.

I filed ticket [#217](https://github.com/scheibler/khard/issues/217), but it's just a plea for stable APIs as the removal looks intentional.  In any case deoplete-khard is broken; since I can't find any explanation about why the method was released, I have no idea what's supposed to replace it.

**Comment by d7415** [comment]
fwiw it looks like it's just a `s/get_email_addresses/emails/` at https://github.com/nicoe/deoplete-khard/blob/master/rplugin/python3/deoplete/sources/khard_emails.py#L40

**Comment by d7415** [comment]
I've been corrected: `s/get_email_addresses()/emails/` as it's now a property.
