### ISSUE TITLE
Help to set up the plugin

### ISSUE THREAD

**Issue by arponero** [nicoe/deoplete-khard#5]
Hi,

I am new to deoplete, so I am not totally sure how to set up everything to make deoplete-khard work.

Everything is installed correctly, so I guess I am missing something in the nvim configuration file.

After :set filetype=mail, I start writing an email, but after writing something like `To: Fran` nothing happens, even there are a lot of Franks in my khard vcards. After `<c-x><c-o>` the result is:

`-- Omni completion (^O^N^P) Pattern not found`

I would need some help to make it work. Thanks in advance!

Best,
Jaime

**Comment by jorsn** [comment]
Have you solved this? It might be because a khard update broke deoplete-khard. I don't know since when but it is fixed in #6.
